import Provider from "./Provider";
import Sidebar from "./Sidebar";
import "./globals.css";
import { Poppins } from "next/font/google";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Provider>
        <body className={poppins.className}>
          <div className="bg-gray-50/50">
            <Sidebar />
            <main className="relative ml-64 flex min-h-screen flex-col items-stretch justify-stretch">
              {children}
            </main>
          </div>
        </body>
      </Provider>
    </html>
  );
}
